@startuml
actor User as USER
participant Frontend as FE
participant "<<component>>\nFileStorageService" as CLOUDSERV
participant "<<component>>\nDataAccessService" as DATASERV
database "<<external system>>\nESG Database" as DATA
participant "<<external system>>\nCloud Storage" as CLOUD

USER -> FE : wants to import/create {resource}
activate FE

FE --> USER : asks for the required information to import/create {resource}
deactivate FE
activate USER

USER -> FE : provides {resource} information
deactivate USER
activate FE

alt Image is included

    FE -> CLOUDSERV : upload(image)
    activate CLOUDSERV

    CLOUDSERV --> CLOUD : upload(image)
    activate CLOUD
    CLOUD --> CLOUDSERV : returns public image URL
    deactivate CLOUD

    CLOUDSERV --> FE : public image URL
    deactivate CLOUDSERV

end alt

note right of FE
In case {resource} is a metric, data includes image public URL
end note

FE -> DATASERV : create(resource data)
activate DATASERV

DATASERV --> DATA : insert({resource})

DATASERV --> FE : confirmation
deactivate DATASERV

alt Success
    FE --> USER : operation was successful
else Failure
    FE --> USER : show error message
deactivate FE
end alt

deactivate FE
@enduml
