@startuml

actor User as USER
participant Frontend as FE
participant "<<component>>\nDataAccessService" as DATASERV
database "<<external system>>\nESG Database" as DATA

USER -> FE : wants to see page with information
activate FE

alt Filtered search
    FE --> USER : asks for specific filters
    deactivate FE
    activate USER

    USER -> FE : provides filter values
    deactivate USER
    activate FE
end alt

FE -> DATASERV : find(with or without filters)
activate DATASERV

DATASERV -> DATA : find(query with optional filters)

note right DATASERV
If the resource being retrieved is a metric,
the result also includes its image URL
end note

DATASERV --> FE : results
deactivate DATASERV

FE --> USER : displays page with the information
deactivate FE

@enduml
